#jpa:
##  database: postgresql
##  show-sql: true
##  hibernate:
##    ddl-auto: update
##  properties:
##    hibernate:
##      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
##
##  datasource:
##    url: jdbc:postgresql://127.0.0.1:5432/db2
##    username: postgres
##    password: admin
##    driver-class-name: org.postgresql.Driver
#\u8FDE\u63A5\u6C60\u7684\u914D\u7F6E
server:
  port: 10002
spring:
  application:
    name: spring-boot-swagger
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/fgo
    username: postgres
    password: admin
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetch-registry: true  #服务发现开关
    service-url:
      defaultZone: http://localhost:8761/eureka/ #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id

