#jpa:
##  database: postgresql
##  show-sql: true
##  hibernate:
##    ddl-auto: update
##  properties:
##    hibernate:
##      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
##
##  datasource:
##    url: jdbc:postgresql://127.0.0.1:5432/db2
##    username: postgres
##    password: admin
##    driver-class-name: org.postgresql.Driver
#\u8FDE\u63A5\u6C60\u7684\u914D\u7F6E
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/fgo
    username: postgres
    password: admin
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
